// <auto-generated />
using System;
using HomeFoodDelivery.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeFoodDelivery.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260604152611_AddPincodeAndGoogleAuth")]
    partial class AddPincodeAndGoogleAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.DailyMenu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailablePortions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MenuDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerPortion")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MenuId");

                    b.HasIndex("CookId");

                    b.HasIndex("ShiftId");

                    b.ToTable("DailyMenus");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.DeliveryZone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServicingNeighborhoods")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TechParkName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ZoneId");

                    b.ToTable("DeliveryZones");

                    b.HasData(
                        new
                        {
                            ZoneId = 1,
                            IsActive = true,
                            ServicingNeighborhoods = "CV Raman Nagar, Mahadevapura, Indiranagar",
                            TechParkName = "Bagmane Tech Park"
                        },
                        new
                        {
                            ZoneId = 2,
                            IsActive = true,
                            ServicingNeighborhoods = "Hebbal, Nagawara, Thanisandra",
                            TechParkName = "Manyata Tech Park"
                        },
                        new
                        {
                            ZoneId = 3,
                            IsActive = true,
                            ServicingNeighborhoods = "Bellandur, Marathahalli, Sarjapur Road",
                            TechParkName = "RMZ Ecospace"
                        },
                        new
                        {
                            ZoneId = 4,
                            IsActive = true,
                            ServicingNeighborhoods = "Electronic City, Bommanahalli",
                            TechParkName = "Electronic City Phase 1"
                        });
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.MealShift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("CutoffTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DeliveryTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("EntryOpenTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ShiftId");

                    b.ToTable("MealShifts");

                    b.HasData(
                        new
                        {
                            ShiftId = 1,
                            CutoffTime = new TimeSpan(0, 7, 30, 0, 0),
                            DeliveryTime = new TimeSpan(0, 8, 15, 0, 0),
                            EntryOpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            ShiftName = "Breakfast"
                        },
                        new
                        {
                            ShiftId = 2,
                            CutoffTime = new TimeSpan(0, 11, 0, 0, 0),
                            DeliveryTime = new TimeSpan(0, 12, 0, 0, 0),
                            EntryOpenTime = new TimeSpan(0, 9, 0, 0, 0),
                            ShiftName = "Lunch"
                        },
                        new
                        {
                            ShiftId = 3,
                            CutoffTime = new TimeSpan(0, 18, 30, 0, 0),
                            DeliveryTime = new TimeSpan(0, 19, 30, 0, 0),
                            EntryOpenTime = new TimeSpan(0, 15, 0, 0, 0),
                            ShiftName = "Dinner"
                        });
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("MenuId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pincode")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.DailyMenu", b =>
                {
                    b.HasOne("HomeFoodDelivery.Api.Models.User", "Cook")
                        .WithMany()
                        .HasForeignKey("CookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeFoodDelivery.Api.Models.MealShift", "MealShift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cook");

                    b.Navigation("MealShift");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.Order", b =>
                {
                    b.HasOne("HomeFoodDelivery.Api.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeFoodDelivery.Api.Models.DailyMenu", "DailyMenu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DailyMenu");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.User", b =>
                {
                    b.HasOne("HomeFoodDelivery.Api.Models.DeliveryZone", "DeliveryZone")
                        .WithMany()
                        .HasForeignKey("ZoneId");

                    b.Navigation("DeliveryZone");
                });
#pragma warning restore 612, 618
        }
    }
}
