// <auto-generated />
using System;
using HomeFoodDelivery.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeFoodDelivery.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260607061431_AddCommunityHubsupdates")]
    partial class AddCommunityHubsupdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.CookFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CookFavorites");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.CookFollower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CookFollowers");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.DailyMenu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailablePortions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MenuDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PreparationTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PricePerPortion")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MenuId");

                    b.HasIndex("CookId");

                    b.HasIndex("ShiftId");

                    b.ToTable("DailyMenus");

                    b.HasData(
                        new
                        {
                            MenuId = 101,
                            AvailablePortions = 30,
                            CookId = 1,
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Spicy and crispy dosa with authentic Nellore karam.",
                            DishName = "Nellore Karam Dosa",
                            IsVegetarian = true,
                            MenuDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PreparationTimeMinutes = 30,
                            PricePerPortion = 70.00m,
                            ShiftId = 1
                        },
                        new
                        {
                            MenuId = 102,
                            AvailablePortions = 25,
                            CookId = 3,
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft steaming idlis served with a cup of fresh ginger tea.",
                            DishName = "Idli & Ginger Tea",
                            IsVegetarian = true,
                            MenuDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PreparationTimeMinutes = 30,
                            PricePerPortion = 50.00m,
                            ShiftId = 1
                        },
                        new
                        {
                            MenuId = 103,
                            AvailablePortions = 20,
                            CookId = 1,
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic local nati style donne chicken biryani.",
                            DishName = "Nati Style Donne Chicken Biryani",
                            IsVegetarian = true,
                            MenuDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PreparationTimeMinutes = 30,
                            PricePerPortion = 180.00m,
                            ShiftId = 2
                        },
                        new
                        {
                            MenuId = 104,
                            AvailablePortions = 15,
                            CookId = 3,
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Slow-cooked authentic dum biryani with rich spices.",
                            DishName = "Hyderabadi Chicken Dum Biryani",
                            IsVegetarian = true,
                            MenuDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PreparationTimeMinutes = 30,
                            PricePerPortion = 240.00m,
                            ShiftId = 2
                        },
                        new
                        {
                            MenuId = 105,
                            AvailablePortions = 10,
                            CookId = 1,
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rich, flavorful, and tender mutton biryani.",
                            DishName = "Nellore Mutton Biryani",
                            IsVegetarian = true,
                            MenuDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PreparationTimeMinutes = 30,
                            PricePerPortion = 320.00m,
                            ShiftId = 3
                        },
                        new
                        {
                            MenuId = 106,
                            AvailablePortions = 12,
                            CookId = 3,
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium rich halwa loaded with roasted dry fruits.",
                            DishName = "Shahi Dry Fruit Halwa",
                            IsVegetarian = true,
                            MenuDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PreparationTimeMinutes = 30,
                            PricePerPortion = 120.00m,
                            ShiftId = 3
                        },
                        new
                        {
                            MenuId = 107,
                            AvailablePortions = 15,
                            CookId = 1,
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Creamy dessert overloaded with real fruits and nuts.",
                            DishName = "Fruit N Nut Fantasy Ice Cream",
                            IsVegetarian = true,
                            MenuDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PreparationTimeMinutes = 30,
                            PricePerPortion = 90.00m,
                            ShiftId = 3
                        });
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.DeliveryZone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DropOffInstructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("HubContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("HubName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("ServicingNeighborhoods")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TechParkName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ZoneId");

                    b.ToTable("DeliveryZones");

                    b.HasData(
                        new
                        {
                            ZoneId = 1,
                            IsActive = true,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            ServicingNeighborhoods = "CV Raman Nagar, Mahadevapura, Indiranagar",
                            TechParkName = "Bagmane Tech Park"
                        },
                        new
                        {
                            ZoneId = 2,
                            IsActive = true,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            ServicingNeighborhoods = "Hebbal, Nagawara, Thanisandra",
                            TechParkName = "Manyata Tech Park"
                        },
                        new
                        {
                            ZoneId = 3,
                            IsActive = true,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            ServicingNeighborhoods = "Bellandur, Marathahalli, Sarjapur Road",
                            TechParkName = "RMZ Ecospace"
                        },
                        new
                        {
                            ZoneId = 4,
                            IsActive = true,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            ServicingNeighborhoods = "Electronic City, Bommanahalli",
                            TechParkName = "Electronic City Phase 1"
                        });
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.MealShift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("CutoffTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DeliveryTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("EntryOpenTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ShiftId");

                    b.ToTable("MealShifts");

                    b.HasData(
                        new
                        {
                            ShiftId = 1,
                            CutoffTime = new TimeSpan(0, 7, 30, 0, 0),
                            DeliveryTime = new TimeSpan(0, 8, 15, 0, 0),
                            EntryOpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            ShiftName = "Breakfast"
                        },
                        new
                        {
                            ShiftId = 2,
                            CutoffTime = new TimeSpan(0, 11, 0, 0, 0),
                            DeliveryTime = new TimeSpan(0, 12, 0, 0, 0),
                            EntryOpenTime = new TimeSpan(0, 9, 0, 0, 0),
                            ShiftName = "Lunch"
                        },
                        new
                        {
                            ShiftId = 3,
                            CutoffTime = new TimeSpan(0, 18, 30, 0, 0),
                            DeliveryTime = new TimeSpan(0, 19, 30, 0, 0),
                            EntryOpenTime = new TimeSpan(0, 15, 0, 0, 0),
                            ShiftName = "Dinner"
                        });
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("MenuId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReviewId");

                    b.HasIndex("CookId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("KitchenAddress")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("KitchenName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pincode")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("YouTubeUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.WalletTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("WalletId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.CookFavorite", b =>
                {
                    b.HasOne("HomeFoodDelivery.Api.Models.User", "Cook")
                        .WithMany()
                        .HasForeignKey("CookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeFoodDelivery.Api.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cook");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.CookFollower", b =>
                {
                    b.HasOne("HomeFoodDelivery.Api.Models.User", "Cook")
                        .WithMany()
                        .HasForeignKey("CookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeFoodDelivery.Api.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cook");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.DailyMenu", b =>
                {
                    b.HasOne("HomeFoodDelivery.Api.Models.User", "Cook")
                        .WithMany()
                        .HasForeignKey("CookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeFoodDelivery.Api.Models.MealShift", "MealShift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cook");

                    b.Navigation("MealShift");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.Order", b =>
                {
                    b.HasOne("HomeFoodDelivery.Api.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeFoodDelivery.Api.Models.DailyMenu", "DailyMenu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DailyMenu");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.Review", b =>
                {
                    b.HasOne("HomeFoodDelivery.Api.Models.User", "Cook")
                        .WithMany()
                        .HasForeignKey("CookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeFoodDelivery.Api.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeFoodDelivery.Api.Models.User", null)
                        .WithMany("Reviews")
                        .HasForeignKey("UserId");

                    b.Navigation("Cook");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.User", b =>
                {
                    b.HasOne("HomeFoodDelivery.Api.Models.DeliveryZone", "DeliveryZone")
                        .WithMany()
                        .HasForeignKey("ZoneId");

                    b.Navigation("DeliveryZone");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.Wallet", b =>
                {
                    b.HasOne("HomeFoodDelivery.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.WalletTransaction", b =>
                {
                    b.HasOne("HomeFoodDelivery.Api.Models.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.User", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("HomeFoodDelivery.Api.Models.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
